# Generated by Django 4.0.4 on 2022-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_pontuacaoquizz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_projeto',
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
